name: Update RSS

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt
      - run: python generate_rss.py

      - name: Commit RSS
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add rss.xml
          git commit -m "Update RSS" || exit 0
          git push
